version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for nmaven
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
